apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: TODO-FRONTEND-IMAGE
    newName: ghcr.io/eldemarkki/todo-frontend
  - name: TODO-BACKEND-IMAGE
    newName: ghcr.io/eldemarkki/todo-backend
  - name: RANDOM-TODO-JOB-IMAGE
    newName: ghcr.io/eldemarkki/random-todo-job
resources:
  - the_project/manifests/namespace.yaml
  - the_project/manifests/configmap.yaml
  - the_project/manifests/persistentvolumeclaim.yaml
  - the_project/manifests/deployment.yaml
  - the_project/manifests/service.yaml
  - todo-backend/manifests/configmap.yaml
  - todo-backend/manifests/database.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - the_project/manifests/gateway.yaml
  - the_project/manifests/route.yaml
  - random-todo-job/manifests/configmap.yaml
  - random-todo-job/manifests/cronjob.yaml
