apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
  namespace: project
data:
  HOST: "0.0.0.0"
  PORT: "3000"
  IMAGE_CACHE_ROOT: "/mnt/todo-image-cache"
  IMAGE_CACHE_TTL_MS: "600000"
  IMAGE_URL: "https://picsum.photos/1200"