apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_CACHE_ROOT
              value: "/mnt/todo-image-cache"
          volumeMounts:
            - mountPath: /mnt/todo-image-cache
              name: todo-image-cache-vol
      volumes:
        - name: todo-image-cache-vol
          persistentVolumeClaim:
            claimName: todo-image-cache
