apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-image-cache
spec:
  storageClassName: todo-image-cache-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
