apiVersion: v1
kind: ConfigMap
metadata:
  name: random-todo-job-config
  namespace: project
data:
  WIKIPEDIA_RANDOM_URL: https://en.wikipedia.org/wiki/Special:Random
  TODO_BACKEND_URL: http://todo-backend-svc:2345/todos
