apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo-job
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: random-todo-job
              image: RANDOM-TODO-JOB-IMAGE
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: random-todo-job-config
          restartPolicy: OnFailure
