apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pong-claim
  namespace: exercises
spec:
  storageClassName: main-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi