apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: pingpong-app:latest
          imagePullPolicy: Never
          env:
            - name: PONG_PATH
              value: /app/pong/pong.txt
          volumeMounts:
            - name: pong-file
              mountPath: /app/pong
      volumes:
        - name: pong-file
          persistentVolumeClaim:
            claimName: pong-claim