apiVersion: v1
kind: Service
metadata:
  name: todo-app-postgres-svc
  namespace: project
spec:
  clusterIP: None
  selector:
    app: todo-app-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-postgres
  namespace: project
spec:
  serviceName: todo-app-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-postgres
  template:
    metadata:
      labels:
        app: todo-app-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          envFrom:
            - configMapRef:
                name: project-backend-config
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
